Move to new carpet settings manager
fxmorin/carpet-fixes pull request #111
Opened 2022-10-05 07:18 UTC by adryd325

TODO:
- [ ] Fix CarpetRulePrinter crashing cause translations aren't loaded early enough

Other notable changes:
- Update carpet version to 1.4.83
- Update minecraft version and mappings to 1.19.1

2022-10-05 07:27 UTC, fxmorin requested changes

2022-10-05 07:27 UTC, fxmorin commented on src/main/java/carpetfixes/mixins/entityFixes/FallingBlockEntity_portalsMixin.java
> +            this.tickPortal(); // Improperly named, it's used for gateways too
You can remove that comment now that the naming makes sense

2022-10-05 07:27 UTC, FxMorin commented on src/main/java/carpetfixes/settings/CustomSettingsManager.java
> -            }
Was this removed because its handled by carpet now?

2022-10-05 11:41 UTC, adryd325 commented on src/main/java/carpetfixes/settings/CustomSettingsManager.java
> -            }
It looks to have been removed from carpet
I can readd if you'd like, It just doesnt look necesary to generate the wiki
or at least I couldnt figure out what it did

2022-10-08 16:07 UTC, adryd325 commented
did some super quick sanity tests to make sure i didnt break anthing egregious and this looks ready to merge

2022-10-09 17:17 UTC, merged